// test-predictor: deterministic parity checks for the two predictors.
//
//   test-predictor --lewm  MODEL.gguf --ref tests/fixtures/ref/lewm-pusht [options]
//   test-predictor --vjepa2 MODEL.gguf --ref tests/fixtures/ref/vjepa2-vitl-fpc64-256 [--samples a,b] [options]
//   test-predictor --vjepa2 MODEL.gguf --case DIR        (numpy cross-check: DIR/{enc,ctx_idx,tgt_idx,pred}.npy)
//   test-predictor --ac    MODEL.gguf --ref tests/fixtures/ref/vjepa2-ac-vitg [options]
//   options: [--threads N] [--no-flash] [--kv-f32|--kv-f16] [--min-cos X] [--modality auto|video|image] [--quiet]
//
// LeWM (f32 thresholds cos >= 0.9999):
//   * pred_next of every image sample (T = 1) and pred_seq of the 3-frame sequence sample (T = 3),
//     both against the PyTorch dump;
//   * causality: row t of the T = 3 run equals the prefix-only run over frames 0..t, and perturbing
//     a *later* frame's embedding leaves the earlier output rows bit-identical;
//   * jepa_lewm_rollout: step 0 of a rollout seeded with emb_seq[0] equals jepa_lewm_predict(T = 1).
// V-JEPA 2: the masked predictor over the reference encoder tokens with context = target = every
//   token (the HF default pass) against `predictor_last_hidden_state`.
// V-JEPA 2-AC (jepa.pred.kind == "ac"), against the Meta world-model dump:
//   * jepa_ac_predict (T = 1) vs `step1.pred_next` and jepa_ac_predict_all (T = 2) vs `step2.pred_seq`;
//   * block-causality: the T = 1 answer reproduces row block 0 of the T = 2 run, and perturbing the
//     SECOND frame's context leaves block 0 bit-identical while moving block 1 visibly;
//   * jepa_ac_rollout over K candidates x H steps vs `rollout.rollout`, with the poses generated by
//     jepa_ac_next_state (states = NULL) -- which is also checked against scipy's `next_state_ref`;
//   * K batched on the batch axis == K sequential single-candidate rollouts, bit-identical at f32;
//   * jepa_ac_energy vs `rollout.rollout_energy`;
//   * `rollout_seed2`: the n_seed = 2 rollout through jepa_ac_rollout_ex, its `seed_actions`
//     argument shown to matter, and the cached-context handle (jepa_ac_context_new / _update /
//     _trim / jepa_ac_rollout_cached) shown to be bit-identical to the explicit-context path;
//   * `cem`: jepa_ac_plan replaying the random draws Meta's own cem() made, against the plan it
//     returned.
// --modality selects the V-JEPA 2.1 modality vector (pred.mod_embed_video / _img) for --case runs:
//   the 576-token image case only reaches parity with `image` (see docs/parity.md, predictor table).
// Exit status 1 on any failure.
#include "jepa.h"
#include "npy.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

struct metrics {
    double cos_mean = 0, cos_min = 1, max_abs = 0, rel_max = 0;
    int64_t rows = 0;
};

static metrics compare(const float * a, const float * b, int64_t rows, int64_t dim) {
    metrics m;
    m.rows = rows;
    double cos_sum = 0, ref_max = 0;
    for (int64_t r = 0; r < rows; r++) {
        double dot = 0, na = 0, nb = 0;
        for (int64_t d = 0; d < dim; d++) {
            const double x = a[r * dim + d], y = b[r * dim + d];
            dot += x * y; na += x * x; nb += y * y;
            const double diff = std::fabs(x - y);
            if (diff > m.max_abs) m.max_abs = diff;
            if (std::fabs(y) > ref_max) ref_max = std::fabs(y);
        }
        const double c = dot / (std::sqrt(na) * std::sqrt(nb) + 1e-30);
        cos_sum += c;
        if (c < m.cos_min) m.cos_min = c;
    }
    m.cos_mean = rows ? cos_sum / rows : 0;
    m.rel_max = m.max_abs / (ref_max + 1e-30);
    return m;
}

static int g_fail = 0;
static bool g_quiet = false;

// thresholds mirror the image-family rows of tests/test-parity.cpp (docs/parity.md "Thresholds"):
// f32 mean/worst cosine >= 0.9999 and rel_max <= the length-aware bound below; f16 mean >= 0.9999,
// worst >= 0.99; quantized mean >= 0.999, worst >= 0.98.  The worst-row floors are dtype noise, not
// graph error: the numpy spec on the same GGUF bottoms out at cos_min 0.99897 for q8_0 (weight
// quantisation alone) on archery_f16.
struct thresholds { double min_mean, min_min, max_rel; };

// f32 rel_max bound, widened with the number of rows: max|a-b| grows like the accumulated round-off
// of the longest reduction in the graph (~sqrt(N) for attention over N rows).  1e-3 up to the
// 2048-row reference point, 2e-3 at 8192 rows (the 64-frame V-JEPA 2 clip measures 1.22e-3 there at
// cosine 1.000000, the 2.1 predictor 1.07e-3 at 4608 rows at cosine 1.0000000).  Same formula as
// test-parity.cpp.
static double rel_bound(double base, int64_t rows) {
    if (base <= 0) return -1.0;
    return std::fmax(base, base * std::sqrt((double) rows / 2048.0));
}

// On a GPU there is no f32 tier: ggml's CUDA "F32" mul_mat is TF32 (the algo enum, which
// GGML_PREC_F32 cannot undo), the attention path is F16-accumulate, and ggml_norm uses the
// one-pass variance -- docs/parity.md "Parity on a GPU", same reasoning as test-parity's POLICY. An f32 file
// is therefore judged with the f16 bars there, and every GPU tier gates rel_max as well, because a
// wrong ggml_norm variance is a per-row *scale* error that cosine is blind to by construction.
static thresholds thresholds_for(int ftype, bool gpu) {
    if (gpu) {
        if (ftype == 0 || ftype == 1) return {0.9999, 0.99, 2e-2};
        return {0.999, 0.98, 8e-2};
    }
    if (ftype == 0) return {0.9999, 0.9999, 1e-3};
    if (ftype == 1) return {0.9999, 0.99, -1.0};
    return {0.999, 0.98, -1.0};
}

// self-consistency (prefix vs full run, rollout vs predict): the same graph on the same numbers,
// so anything beyond float32 round-off is a bug
static const thresholds exact = {0.9999999, 0.9999999, 1e-5};

// The one exception: the T = 1 prefix is not the same graph as the T = 3 run -- a single query row
// and no causal mask take ggml's per-row flash kernel (docs/ggml-notes.md §1) -- so for an f16 /
// quantized file its row matches only to dtype round-off (lewm-pusht-f16 measures max|d| 2.4e-4,
// rel 2.0e-4; T >= 2 is bit-identical at every dtype).  A broken causal mask would let row 0 see the
// later frames, which moves the cosine by ~1e-1, far below this bar.
static const thresholds exact_dtype = {0.999999, 0.999999, 1e-3};

static void check(const char * what, const metrics & m, const thresholds & t, double ms = -1) {
    const double min_cos = t.min_min, max_rel = rel_bound(t.max_rel, m.rows);
    const bool ok = m.cos_mean >= t.min_mean && m.cos_min >= min_cos && (max_rel <= 0 || m.rel_max <= max_rel);
    if (!ok) g_fail++;
    if (!g_quiet || !ok) {
        printf("  %-44s rows=%-6lld cos_mean=%.7f cos_min=%.7f max|d|=%.3e rel=%.3e", what,
               (long long) m.rows, m.cos_mean, m.cos_min, m.max_abs, m.rel_max);
        if (ms >= 0) printf(" %8.2f ms", ms);
        printf("  %s\n", ok ? "OK" : "FAIL");
        if (!ok) {
            char rel[48] = "";
            if (max_rel > 0) snprintf(rel, sizeof(rel), ", rel <= %.3e (%lld rows)", max_rel, (long long) m.rows);
            printf("  %-44s bars: cos_mean >= %g, cos_min >= %g%s\n", "", t.min_mean, min_cos, rel);
        }
    }
}

static std::vector<float> load_f32(const std::string & path, int64_t * rows, int64_t * dim) {
    npy::Array a = npy::load(path);
    std::vector<float> v = a.to_f32();
    if (rows) *rows = a.shape.size() >= 2 ? a.shape[0] : 1;
    if (dim)  *dim  = a.shape.empty() ? 0 : a.shape.back();
    return v;
}

static bool exists(const std::string & p) { std::ifstream f(p); return (bool) f; }

// ------------------------------------------------------------------------------------------
// LeWM
// ------------------------------------------------------------------------------------------
static void run_lewm(jepa_context * ctx, jepa_model * model, const std::string & ref, const thresholds & thr,
                     bool lossy) {
    const int D = jepa_model_embed_dim(model);
    const int A = jepa_lewm_action_dim(model);
    printf("LeWM predictor: D=%d action_dim=%d window=%d\n", D, A, jepa_lewm_n_frames(model));

    // per-image samples: T = 1
    for (const char * s : {"coco_000000000139", "coco_000000000285"}) {
        const std::string base = ref + "/" + s;
        if (!exists(base + ".emb.npy")) continue;
        int64_t r, d;
        std::vector<float> emb = load_f32(base + ".emb.npy", &r, &d);
        std::vector<float> act = load_f32(base + ".action.npy", &r, &d);
        std::vector<float> want = load_f32(base + ".pred_next.npy", &r, &d);
        jepa_output out = {};
        if (jepa_lewm_predict(ctx, emb.data(), act.data(), 1, &out) != 0) { printf("  %s: predict failed\n", s); g_fail++; continue; }
        check((std::string(s) + " pred_next (T=1)").c_str(), compare(out.data, want.data(), 1, D), thr,
              jepa_context_last_compute_ms(ctx));
        free(out.data);
    }

    // sequence sample: T = 3, causal
    const std::string seq = ref + "/seq";
    if (!exists(seq + ".emb_seq.npy")) return;
    int64_t T = 0, d = 0;
    std::vector<float> emb = load_f32(seq + ".emb_seq.npy", &T, &d);
    std::vector<float> act = load_f32(seq + ".action_seq.npy", &T, &d);
    std::vector<float> want = load_f32(seq + ".pred_seq.npy", &T, &d);
    jepa_output full = {};
    if (jepa_lewm_predict(ctx, emb.data(), act.data(), (int) T, &full) != 0) { printf("  seq: predict failed\n"); g_fail++; return; }
    check("seq pred_seq (T=3, all rows)", compare(full.data, want.data(), T, D), thr, jepa_context_last_compute_ms(ctx));

    // causality (a): the prefix-only run reproduces row t
    for (int t = 0; t < (int) T; t++) {
        jepa_output pre = {};
        if (jepa_lewm_predict(ctx, emb.data(), act.data(), t + 1, &pre) != 0) { g_fail++; continue; }
        char name[64];
        snprintf(name, sizeof(name), "seq causal prefix T=%d -> row %d", t + 1, t);
        check(name, compare(pre.data + (size_t) t * D, full.data + (size_t) t * D, 1, D),
              (t == 0 && lossy) ? exact_dtype : exact);
        free(pre.data);
    }

    // causality (b): perturbing the LAST frame must not move the earlier output rows at all.
    // The perturbation has to be NON-UNIFORM: the adaLN path starts with a non-affine LayerNorm, so
    // adding the same constant to every channel of a row is absorbed (mean-subtracted) and the test
    // would be vacuous -- move two channels in opposite directions instead.
    {
        std::vector<float> emb2 = emb, act2 = act;
        emb2[(size_t) (T - 1) * D + 0] += 5.0f;
        emb2[(size_t) (T - 1) * D + 1] -= 3.0f;
        act2[(size_t) (T - 1) * A + 0] += 5.0f;
        if (A > 1) act2[(size_t) (T - 1) * A + 1] -= 3.0f;
        jepa_output pert = {};
        if (jepa_lewm_predict(ctx, emb2.data(), act2.data(), (int) T, &pert) != 0) { g_fail++; }
        else {
            double worst = 0;
            for (int64_t i = 0; i < (T - 1) * D; i++) worst = std::fmax(worst, std::fabs(pert.data[i] - full.data[i]));
            const bool ok = worst == 0.0;
            if (!ok) g_fail++;
            printf("  %-44s max|d| on rows 0..%d = %.3e  %s\n", "causality: perturb frame T-1", (int) T - 2, worst,
                   ok ? "OK (bit-identical)" : "FAIL");
            // and the perturbed row itself has to move by a visible amount, or the check proves nothing
            double moved = 0;
            for (int64_t i = (T - 1) * D; i < T * D; i++) moved = std::fmax(moved, std::fabs(pert.data[i] - full.data[i]));
            const bool moved_ok = moved > 1e-2;
            if (!moved_ok) g_fail++;
            printf("  %-44s max|d| on row %d = %.3e  %s\n", "causality: perturbation is visible", (int) T - 1, moved,
                   moved_ok ? "OK (> 1e-2)" : "FAIL (the perturbation is absorbed - test is vacuous)");
            free(pert.data);
        }
    }

    // rollout: step 0 with a single seed frame must equal the T = 1 call
    {
        std::vector<float> steps((size_t) T * D);
        if (jepa_lewm_rollout(ctx, emb.data(), 1, act.data(), (int) T, steps.data()) != 0) { g_fail++; }
        else {
            jepa_output one = {};
            if (jepa_lewm_predict(ctx, emb.data(), act.data(), 1, &one) == 0) {
                check("rollout step 0 == predict(T=1)", compare(steps.data(), one.data, 1, D), exact);
                free(one.data);
            }
            // and step 1 must equal predict(T=2) over [emb0, pred0] with actions [a0, a1]
            std::vector<float> e2((size_t) 2 * D), a2((size_t) 2 * A);
            memcpy(e2.data(), emb.data(), (size_t) D * sizeof(float));
            memcpy(e2.data() + D, steps.data(), (size_t) D * sizeof(float));
            memcpy(a2.data(), act.data(), (size_t) 2 * A * sizeof(float));
            jepa_output two = {};
            if (jepa_lewm_predict(ctx, e2.data(), a2.data(), 2, &two) == 0) {
                check("rollout step 1 == predict(T=2) last row",
                      compare(steps.data() + D, two.data + D, 1, D), exact);
                free(two.data);
            }
        }
    }
    free(full.data);
}

// ------------------------------------------------------------------------------------------
// V-JEPA 2 masked predictor
// ------------------------------------------------------------------------------------------
static void run_vjepa2(jepa_context * ctx, jepa_model * model, const std::string & ref,
                       const std::vector<std::string> & samples, const thresholds & thr, int modality) {
    for (const std::string & s : samples) {
        const std::string base = ref + "/" + s;
        if (!exists(base + ".predictor_last_hidden_state.npy")) { printf("  %s: no reference predictor dump\n", s.c_str()); continue; }
        int64_t n = 0, d = 0;
        std::vector<float> enc_rows = load_f32(base + ".last_hidden_state.npy", &n, &d);
        int64_t nr = 0, dr = 0;
        std::vector<float> want = load_f32(base + ".predictor_last_hidden_state.npy", &nr, &dr);
        jepa_output enc = { enc_rows.data(), n, d };
        std::vector<int32_t> ids((size_t) n);
        for (int64_t i = 0; i < n; i++) ids[i] = (int32_t) i;
        jepa_output out = {};
        if (jepa_predict_mod(ctx, &enc, ids.data(), (int) n, ids.data(), (int) n, 1, modality, &out) != 0) {
            printf("  %s: jepa_predict failed\n", s.c_str());
            g_fail++;
            continue;
        }
        check((s + " predictor_last_hidden_state").c_str(), compare(out.data, want.data(), nr, dr), thr,
              jepa_context_last_compute_ms(ctx));
        free(out.data);
    }
}

// numpy cross-check case: DIR/{enc,ctx_idx,tgt_idx,pred}.npy, written by running
// scripts/jepa_convert/vjepa2_numpy_ref.py::predictor_forward on reference encoder tokens (the
// snippet that generates one is in docs/parity.md, "Results - predictors").  The case has to be
// generated from the SAME GGUF that is tested: the spec runs that file's weights.
static void run_case(jepa_context * ctx, const std::string & dir, const thresholds & thr, int modality) {
    int64_t n = 0, d = 0;
    std::vector<float> enc_rows = load_f32(dir + "/enc.npy", &n, &d);
    npy::Array ci = npy::load(dir + "/ctx_idx.npy"), ti = npy::load(dir + "/tgt_idx.npy");
    std::vector<float> cif = ci.to_f32(), tif = ti.to_f32();
    std::vector<int32_t> cidx(cif.begin(), cif.end()), tidx(tif.begin(), tif.end());
    int64_t nr = 0, dr = 0;
    std::vector<float> want = load_f32(dir + "/pred.npy", &nr, &dr);
    jepa_output enc = { enc_rows.data(), n, d };
    jepa_output out = {};
    if (jepa_predict_mod(ctx, &enc, cidx.data(), (int) cidx.size(), tidx.data(), (int) tidx.size(), 1, modality, &out) != 0) {
        printf("  case %s: jepa_predict failed\n", dir.c_str());
        g_fail++;
        return;
    }
    char name[160];
    snprintf(name, sizeof(name), "case %s (ctx=%zu tgt=%zu)", dir.c_str(), cidx.size(), tidx.size());
    check(name, compare(out.data, want.data(), nr, dr), thr, jepa_context_last_compute_ms(ctx));
    free(out.data);
}
// A rollout feeds its own output back, so a per-call `rel_max` bound says nothing about step h > 0:
// the deviation of step 0 is the input of step 1. What the API actually promises is gated instead —
// the per-row cosine of every step (the tier's bars), the energy VALUE (a pure scale measure, which
// cosine is blind to and which a wrong rollout would move) and the energy RANKING, which is the
// answer a planner reads. `rel` is printed for the record. Measured amplification on a GPU at f32:
// rel 5.7e-03 at step 0 -> 6.3e-02 at step 1, with cos_min 0.99998 -> 0.99725; on the CPU at f32 the
// same two steps stay at 1.2e-05 and 8.7e-05 (docs/parity.md, "V-JEPA 2-AC").
// The cosine bars relax with the step because the error compounds: step h's input is step h-1's
// output. The model used here is the tier's own slack, quadrupled per step —
//   cos_bar(h) = 1 - (1 - cos_bar) * 4^h
// which is 0.9996 at step 1 for a CPU f32 file (measured 1.0000000) and 0.92 for a GPU q8_0 one
// (measured 0.9586). What does NOT relax is the energy ranking below: at every tier and on both
// backends the planner has to pick the same candidate.
static thresholds rollout_tier(const thresholds & thr, int step) {
    const double f = std::pow(4.0, (double) step);
    thresholds t = thr;
    t.min_mean = 1.0 - (1.0 - thr.min_mean) * f;
    t.min_min  = 1.0 - (1.0 - thr.min_min) * f;
    t.max_rel  = -1.0;
    return t;
}


// ------------------------------------------------------------------------------------------
// V-JEPA 2-AC world model
// ------------------------------------------------------------------------------------------
static void run_ac(jepa_context * ctx, jepa_model * model, const std::string & ref, const thresholds & thr,
                   bool gpu) {
    const int64_t D = jepa_model_embed_dim(model);
    const int64_t HW = jepa_ac_tokens_per_frame(model);
    const int A = jepa_ac_action_dim(model), S = jepa_ac_state_dim(model);
    printf("AC predictor: enc_dim=%lld tokens/frame=%lld action_dim=%d state_dim=%d frames<=%d normalize_reps=%s\n",
           (long long) D, (long long) HW, A, S, jepa_ac_max_frames(model),
           jepa_ac_normalize_reps(model) ? "yes" : "no");
    if (HW <= 0) { printf("  not an AC model\n"); g_fail++; return; }

    int64_t r = 0, d = 0;
    // ---- 1. one step (T = 1)
    const std::string s1 = ref + "/step1";
    if (!exists(s1 + ".pred_next.npy")) { printf("  no AC reference dump in %s\n", ref.c_str()); g_fail++; return; }
    std::vector<float> ctx1 = load_f32(s1 + ".context.npy", &r, &d);
    std::vector<float> act1 = load_f32(s1 + ".action.npy", &r, &d);
    std::vector<float> st1  = load_f32(s1 + ".state.npy", &r, &d);
    std::vector<float> want1 = load_f32(s1 + ".pred_next.npy", &r, &d);
    jepa_output o1 = {};
    if (jepa_ac_predict(ctx, ctx1.data(), 1, 1, act1.data(), st1.data(), &o1) != 0) {
        printf("  step1: jepa_ac_predict failed\n"); g_fail++; return;
    }
    check("step1 pred_next (T=1)", compare(o1.data, want1.data(), HW, D), thr, jepa_context_last_compute_ms(ctx));

    // ---- 2. two frames, every row
    const std::string s2 = ref + "/step2";
    std::vector<float> ctx2 = load_f32(s2 + ".context_seq.npy", &r, &d);
    std::vector<float> act2 = load_f32(s2 + ".action_seq.npy", &r, &d);
    std::vector<float> st2  = load_f32(s2 + ".state_seq.npy", &r, &d);
    std::vector<float> want2 = load_f32(s2 + ".pred_seq.npy", &r, &d);
    jepa_output o2 = {};
    if (jepa_ac_predict_all(ctx, ctx2.data(), 2, 1, act2.data(), st2.data(), &o2) != 0) {
        printf("  step2: jepa_ac_predict_all failed\n"); g_fail++; free(o1.data); return;
    }
    check("step2 pred_seq (T=2, all rows)", compare(o2.data, want2.data(), 2 * HW, D), thr,
          jepa_context_last_compute_ms(ctx));
    check("step2 pred_seq block 1 (next frame)",
          compare(o2.data + HW * D, want2.data() + HW * D, HW, D), thr);
    // jepa_ac_predict must return exactly the LAST block of jepa_ac_predict_all
    jepa_output o2last = {};
    if (jepa_ac_predict(ctx, ctx2.data(), 2, 1, act2.data(), st2.data(), &o2last) == 0) {
        check("predict(T=2) == predict_all(T=2) last block",
              compare(o2last.data, o2.data + HW * D, HW, D), exact);
        free(o2last.data);
    } else { g_fail++; }

    // ---- 3. block-causality
    // The T = 1 answer has to be row block 0 of the T = 2 run. On the CPU that is the same numbers in
    // a different graph and comes out bit-identical; on a GPU the two shapes pick different GEMM
    // tilings and attention kernels, so it is judged with the file's tier there (a broken mask would
    // let block 0 read frame 1, which moves the cosine by ~1e-1 -- far below either bar).
    check("causal: T=1 == T=2 block 0", compare(o1.data, o2.data, HW, D), gpu ? thr : exact);
    {
        // Perturb the SECOND frame's context (non-uniformly, so the block's LayerNorm cannot absorb
        // it): block 0 has to stay bit-identical, block 1 has to move.
        std::vector<float> pert = ctx2;
        pert[(size_t) HW * D + 0] += 5.0f;
        pert[(size_t) HW * D + 1] -= 3.0f;
        jepa_output op = {};
        if (jepa_ac_predict_all(ctx, pert.data(), 2, 1, act2.data(), st2.data(), &op) != 0) { g_fail++; }
        else {
            double worst = 0, moved = 0;
            for (int64_t i = 0; i < HW * D; i++) worst = std::fmax(worst, std::fabs(op.data[i] - o2.data[i]));
            for (int64_t i = HW * D; i < 2 * HW * D; i++) moved = std::fmax(moved, std::fabs(op.data[i] - o2.data[i]));
            const bool ok = worst == 0.0, moved_ok = moved > 1e-2;
            if (!ok) g_fail++;
            if (!moved_ok) g_fail++;
            printf("  %-44s max|d| on block 0 = %.3e  %s\n", "causality: perturb frame 1", worst,
                   ok ? "OK (bit-identical)" : "FAIL");
            printf("  %-44s max|d| on block 1 = %.3e  %s\n", "causality: perturbation is visible", moved,
                   moved_ok ? "OK (> 1e-2)" : "FAIL (absorbed - the test would be vacuous)");
            free(op.data);
        }
    }
    free(o1.data);
    free(o2.data);

    // ---- 4. rollout of K candidates x H steps
    const std::string ro = ref + "/rollout";
    if (!exists(ro + ".rollout.npy")) return;
    npy::Array roll = npy::load(ro + ".rollout.npy");     // [K, H, HW, D]
    if (roll.shape.size() != 4) { printf("  rollout dump has rank %zu\n", roll.shape.size()); g_fail++; return; }
    const int K = (int) roll.shape[0], H = (int) roll.shape[1];
    std::vector<float> want_roll = roll.to_f32();
    std::vector<float> seed = load_f32(ro + ".context.npy", &r, &d);
    std::vector<float> goal = load_f32(ro + ".goal.npy", &r, &d);
    std::vector<float> st0  = load_f32(ro + ".state0.npy", &r, &d);
    std::vector<float> acts = npy::load(ro + ".actions.npy").to_f32();       // [K, H, A]
    std::vector<float> want_e = load_f32(ro + ".rollout_energy.npy", &r, &d);

    // jepa_ac_next_state against scipy's compute_new_pose
    {
        std::vector<float> ns = npy::load(ro + ".next_state_ref.npy").to_f32();  // [K, 7]
        std::vector<float> got((size_t) K * S);
        for (int c = 0; c < K; c++) {
            jepa_ac_next_state(model, st0.data(), acts.data() + (size_t) c * H * A, got.data() + (size_t) c * S);
        }
        double worst = 0;
        for (size_t i = 0; i < got.size(); i++) worst = std::fmax(worst, std::fabs(got[i] - ns[i]));
        const bool ok = worst <= 1e-6;
        if (!ok) g_fail++;
        printf("  %-44s max|d| vs scipy = %.3e  %s\n", "jepa_ac_next_state (compute_new_pose)", worst,
               ok ? "OK (<= 1e-6)" : "FAIL");
    }

    std::vector<float> out((size_t) K * H * HW * D);
    if (jepa_ac_rollout(ctx, seed.data(), 1, st0.data(), acts.data(), nullptr, K, H, out.data()) != 0) {
        printf("  rollout failed\n"); g_fail++; return;
    }
    const double roll_ms = jepa_context_last_compute_ms(ctx);
    char name[96];
    std::vector<double> step_rel((size_t) H, 0.0);   // per-step deviation from the reference
    for (int h = 0; h < H; h++) {
        std::vector<float> got((size_t) K * HW * D), ref_h((size_t) K * HW * D);
        for (int c = 0; c < K; c++) {
            memcpy(got.data() + (size_t) c * HW * D, out.data() + ((size_t) c * H + h) * HW * D,
                   (size_t) HW * D * sizeof(float));
            memcpy(ref_h.data() + (size_t) c * HW * D, want_roll.data() + ((size_t) c * H + h) * HW * D,
                   (size_t) HW * D * sizeof(float));
        }
        snprintf(name, sizeof(name), "rollout step %d (K=%d candidates)", h, K);
        const metrics m = compare(got.data(), ref_h.data(), (int64_t) K * HW, D);
        step_rel[h] = m.rel_max;
        check(name, m, rollout_tier(thr, h), h == H - 1 ? roll_ms : -1);
    }

    // ---- 5. the planning energy
    {
        std::vector<float> got_e((size_t) K);
        std::vector<float> last((size_t) K * HW * D);
        for (int c = 0; c < K; c++) {
            memcpy(last.data() + (size_t) c * HW * D, out.data() + ((size_t) c * H + (H - 1)) * HW * D,
                   (size_t) HW * D * sizeof(float));
        }
        jepa_ac_energy(last.data(), goal.data(), K, HW, D, got_e.data());
        double worst = 0, scale = 0;
        for (int c = 0; c < K; c++) {
            worst = std::fmax(worst, std::fabs(got_e[c] - want_e[c]));
            scale = std::fmax(scale, std::fabs(want_e[c]));
        }
        const double rel = worst / (scale + 1e-30);
        // The energy is the scale measure the rollout's cosine bars cannot see. On the CPU at f32 it
        // reproduces the reference to 7.5e-07; the GPU and the lossy tiers inherit their inputs'
        // deviation, so they get the same 5e-03 bar the GPU tier gates `rel_max` with elsewhere.
        // The tier's own worst-row slack, floored at the CPU-f32 bar: 1e-4 for a bit-exact CPU f32
        // file (measured 7.5e-07), 1e-2 for the GPU f32/f16 tiers (3.5e-04 / 7.0e-04) and 2e-2 for a
        // quantized one (6.4e-03).
        const double bar = std::fmax(1e-4, 1.0 - thr.min_min);
        const bool ok = rel <= bar;
        if (!ok) g_fail++;
        printf("  %-44s max|d| = %.3e (rel %.3e over %d candidates, bar %.0e)  %s\n",
               "jepa_ac_energy vs l1(pred, goal)", worst, rel, K, bar, ok ? "OK" : "FAIL");
        // the ranking has to survive too: the argmin is the action the planner would pick
        int best_got = 0, best_ref = 0;
        for (int c = 1; c < K; c++) {
            if (got_e[c] < got_e[best_got]) best_got = c;
            if (want_e[c] < want_e[best_ref]) best_ref = c;
        }
        if (best_got != best_ref) g_fail++;
        printf("  %-44s argmin: ours %d, reference %d  %s\n", "energy ranking (the planner's choice)",
               best_got, best_ref, best_got == best_ref ? "OK" : "FAIL");
    }

    // ---- 5b. caller-supplied poses == the ones jepa_ac_next_state generates. The dump stores the
    // poses compute_new_pose produced for every candidate and step, so passing them in explicitly has
    // to reproduce the states = NULL run exactly (jepa_ac_next_state matches scipy bit-for-bit above).
    {
        std::vector<float> st_seq = npy::load(ro + ".states_seq.npy").to_f32();   // [K, H, S]
        std::vector<float> out2((size_t) K * H * HW * D);
        if (jepa_ac_rollout(ctx, seed.data(), 1, st0.data(), acts.data(), st_seq.data(), K, H, out2.data()) != 0) {
            printf("  rollout with explicit states failed\n");
            g_fail++;
        } else {
            double worst = 0;
            for (size_t i = 0; i < out2.size(); i++) worst = std::fmax(worst, std::fabs(out2[i] - out[i]));
            const bool ok = worst == 0.0;
            if (!ok) g_fail++;
            printf("  %-44s max|d| = %.3e  %s\n", "explicit states == jepa_ac_next_state", worst,
                   ok ? "OK (bit-identical)" : "FAIL");
        }
    }

    // ---- 5c. a longer horizon must agree with a shorter one on the steps they share. The rollout
    // keeps only the PREDICTED frames per candidate (the observed prefix is shared), and the slot
    // bookkeeping changes shape at the last step, where the tail is already full — H = 2 never
    // reaches the interior case, so without this nothing would exercise it.
    {
        const int H2 = H + 2;
        std::vector<float> acts2((size_t) K * H2 * A, 0.0f), out2((size_t) K * H2 * HW * D);
        for (int c = 0; c < K; c++) {
            // the first H actions are the fixture's; the extra steps repeat the last one
            memcpy(acts2.data() + (size_t) c * H2 * A, acts.data() + (size_t) c * H * A,
                   (size_t) H * A * sizeof(float));
            for (int e = H; e < H2; e++) {
                memcpy(acts2.data() + ((size_t) c * H2 + e) * A,
                       acts.data() + ((size_t) c * H + (H - 1)) * A, (size_t) A * sizeof(float));
            }
        }
        if (jepa_ac_rollout(ctx, seed.data(), 1, st0.data(), acts2.data(), nullptr, K, H2, out2.data()) != 0) {
            printf("  longer-horizon rollout failed\n");
            g_fail++;
        } else {
            double worst = 0;
            for (int c = 0; c < K; c++) {
                for (int h = 0; h < H; h++) {
                    const float * a = out2.data() + ((size_t) c * H2 + h) * HW * D;
                    const float * b = out.data() + ((size_t) c * H + h) * HW * D;
                    for (int64_t i = 0; i < HW * D; i++) worst = std::fmax(worst, std::fabs(a[i] - b[i]));
                }
            }
            const bool gpu2 = jepa_model_is_gpu(model);
            const bool ok = gpu2 ? worst <= 1e-2 : worst == 0.0;
            if (!ok) g_fail++;
            snprintf(name, sizeof(name), "H=%d agrees with H=%d on the shared steps", H2, H);
            printf("  %-44s max|d| = %.3e  %s\n", name, worst,
                   ok ? (gpu2 ? "OK (<= 1e-2, GPU)" : "OK (bit-identical)") : "FAIL");
        }
    }

    // ---- 6. batched K == K sequential single-candidate rollouts
    {
        std::vector<float> seq_out((size_t) K * H * HW * D);
        bool ok_all = true;
        for (int c = 0; c < K && ok_all; c++) {
            if (jepa_ac_rollout(ctx, seed.data(), 1, st0.data(), acts.data() + (size_t) c * H * A, nullptr,
                                1, H, seq_out.data() + (size_t) c * H * HW * D) != 0) {
                ok_all = false;
            }
        }
        if (!ok_all) { printf("  sequential rollout failed\n"); g_fail++; }
        else {
            // Per step, so the compounding is visible rather than hidden in one number. On the CPU
            // every step is bit-identical -- the K items share the graph but never a reduction, which
            // is the whole claim of putting candidates on the batch axis. On a GPU the tiling changes
            // with the batch shape, and step h inherits step h-1's deviation, so the bar there is the
            // relative one the GPU tiers use, doubled per step.
            for (int h = 0; h < H; h++) {
                double worst = 0, scale = 0;
                for (int c = 0; c < K; c++) {
                    const size_t off = ((size_t) c * H + h) * HW * D;
                    for (int64_t i = 0; i < HW * D; i++) {
                        worst = std::fmax(worst, std::fabs(seq_out[off + i] - out[off + i]));
                        scale = std::fmax(scale, std::fabs(out[off + i]));
                    }
                }
                const double rel = worst / (scale + 1e-30);
                // The question with an answer on a GPU is whether BATCHING costs more than the
                // backend and dtype already cost: bar it at 4x the batched-vs-reference deviation of
                // the same step, never tighter than the GPU tier's own 2e-2. The `sequential vs
                // reference` row below closes the loop -- both paths have to clear the same tier, so
                // a bar that scales with the backend's error cannot hide a batching bug.
                const double bar = std::fmax(2e-2, 4.0 * step_rel[h]);
                const bool ok = gpu ? rel <= bar : worst == 0.0;
                if (!ok) g_fail++;
                std::vector<float> sq((size_t) K * HW * D), rf((size_t) K * HW * D);
                for (int c = 0; c < K; c++) {
                    memcpy(sq.data() + (size_t) c * HW * D, seq_out.data() + ((size_t) c * H + h) * HW * D,
                           (size_t) HW * D * sizeof(float));
                    memcpy(rf.data() + (size_t) c * HW * D, want_roll.data() + ((size_t) c * H + h) * HW * D,
                           (size_t) HW * D * sizeof(float));
                }
                snprintf(name, sizeof(name), "sequential (K=1) vs reference, step %d", h);
                check(name, compare(sq.data(), rf.data(), (int64_t) K * HW, D), rollout_tier(thr, h));
                snprintf(name, sizeof(name), "batched K == sequential K, step %d", h);
                if (gpu) {
                    printf("  %-44s max|d| = %.3e rel = %.3e (bar %.0e)  %s\n", name, worst, rel, bar,
                           ok ? "OK" : "FAIL");
                } else {
                    printf("  %-44s max|d| = %.3e  %s\n", name, worst,
                           ok ? "OK (bit-identical)" : "FAIL");
                }
            }
        }
    }
}

// The `rollout_seed2` sample: the same K x H rollout, but from TWO observed context frames, with the
// real action between them as `seed_actions`. Meta's own loop never has more than one context frame,
// so the fixture was produced by running THEIR predictor on a conditioning layout the dump script
// fixes explicitly (scripts/dump_reference.py, "5."). This is the only thing that exercises
// jepa_ac_rollout_ex's n_seed > 1 path, which the receding-horizon planner of 7.2 lives on.
static void run_ac_seed2(jepa_context * ctx, jepa_model * model, const std::string & ref,
                         const thresholds & thr, bool gpu) {
    const std::string ro = ref + "/rollout_seed2";
    if (!exists(ro + ".rollout.npy")) return;
    const int64_t D = jepa_model_embed_dim(model);
    const int64_t HW = jepa_ac_tokens_per_frame(model);
    const int A = jepa_ac_action_dim(model), S = jepa_ac_state_dim(model);
    int64_t r = 0, d = 0;
    npy::Array roll = npy::load(ro + ".rollout.npy");        // [K, H, HW, D]
    const int K = (int) roll.shape[0], H = (int) roll.shape[1];
    std::vector<float> want = roll.to_f32();
    std::vector<float> seed = load_f32(ro + ".context.npy", &r, &d);          // [2*HW, D]
    std::vector<float> sa   = load_f32(ro + ".seed_actions.npy", &r, &d);     // [1, A]
    std::vector<float> ss   = load_f32(ro + ".seed_states.npy", &r, &d);      // [2, S]
    std::vector<float> acts = npy::load(ro + ".actions.npy").to_f32();        // [K, H, A]
    const int n_seed = (int) (seed.size() / (size_t) (HW * D));

    std::vector<float> out((size_t) K * H * HW * D);
    if (jepa_ac_rollout_ex(ctx, seed.data(), n_seed, sa.data(), ss.data(), acts.data(), nullptr,
                           K, H, out.data()) != 0) {
        printf("  rollout_seed2 failed\n");
        g_fail++;
        return;
    }
    const double ms = jepa_context_last_compute_ms(ctx);
    char name[96];
    for (int h = 0; h < H; h++) {
        std::vector<float> got((size_t) K * HW * D), rf((size_t) K * HW * D);
        for (int c = 0; c < K; c++) {
            memcpy(got.data() + (size_t) c * HW * D, out.data() + ((size_t) c * H + h) * HW * D,
                   (size_t) HW * D * sizeof(float));
            memcpy(rf.data() + (size_t) c * HW * D, want.data() + ((size_t) c * H + h) * HW * D,
                   (size_t) HW * D * sizeof(float));
        }
        snprintf(name, sizeof(name), "n_seed=2 rollout step %d (K=%d)", h, K);
        check(name, compare(got.data(), rf.data(), (int64_t) K * HW, D), rollout_tier(thr, h),
              h == H - 1 ? ms : -1);
    }
    // seed_actions has to MATTER: with NULL the earlier observed frame reuses the candidate's first
    // planned action instead of the real one, which must move the answer. Without this the test
    // would pass even if the argument were ignored.
    {
        std::vector<float> out2((size_t) K * H * HW * D);
        if (jepa_ac_rollout(ctx, seed.data(), n_seed, ss.data(), acts.data(), nullptr, K, H, out2.data()) == 0) {
            double moved = 0;
            for (size_t i = 0; i < out2.size(); i++) moved = std::fmax(moved, std::fabs(out2[i] - out[i]));
            const bool ok = moved > 1e-2;
            if (!ok) g_fail++;
            printf("  %-44s max|d| = %.3e  %s\n", "seed_actions changes the answer", moved,
                   ok ? "OK (> 1e-2)" : "FAIL (the argument is ignored)");
        } else { g_fail++; }
    }

    // ---- the cached context handle over the same two observed frames
    jepa_ac_context * h = jepa_ac_context_new(ctx, seed.data(), n_seed, sa.data(), ss.data());
    if (!h) { printf("  jepa_ac_context_new failed\n"); g_fail++; return; }
    if (jepa_ac_context_n_frames(h) != n_seed) { printf("  handle holds the wrong frame count\n"); g_fail++; }
    std::vector<float> outc((size_t) K * H * HW * D);
    if (jepa_ac_rollout_cached(ctx, h, acts.data(), nullptr, K, H, outc.data()) != 0) {
        printf("  jepa_ac_rollout_cached failed\n");
        g_fail++;
    } else {
        double worst = 0, scale = 0;
        for (size_t i = 0; i < outc.size(); i++) {
            worst = std::fmax(worst, std::fabs(outc[i] - out[i]));
            scale = std::fmax(scale, std::fabs(out[i]));
        }
        // Same graph, same numbers — the handle only changes where the bytes come from. Bit-identical
        // on the CPU; on a GPU the device-resident tensor is the same memory, so it is exact there too.
        const bool ok = worst == 0.0;
        if (!ok) g_fail++;
        printf("  %-44s max|d| = %.3e  %s\n", "cached context == explicit context", worst,
               ok ? "OK (bit-identical)" : "FAIL");
        (void) scale;
    }
    // update(): appending the first predicted frame has to equal a handle built from all three.
    {
        std::vector<float> three((size_t) (n_seed + 1) * HW * D);
        memcpy(three.data(), seed.data(), seed.size() * sizeof(float));
        memcpy(three.data() + seed.size(), out.data(), (size_t) HW * D * sizeof(float));  // cand 0, step 0
        std::vector<float> a3((size_t) n_seed * A), s3((size_t) (n_seed + 1) * S);
        memcpy(a3.data(), sa.data(), (size_t) (n_seed - 1) * A * sizeof(float));
        memcpy(a3.data() + (size_t) (n_seed - 1) * A, acts.data(), (size_t) A * sizeof(float));
        memcpy(s3.data(), ss.data(), ss.size() * sizeof(float));
        jepa_ac_next_state(model, ss.data() + (size_t) (n_seed - 1) * S, acts.data(),
                           s3.data() + (size_t) n_seed * S);
        if (jepa_ac_context_update(h, out.data(), acts.data(), s3.data() + (size_t) n_seed * S) != 0) {
            printf("  jepa_ac_context_update failed\n");
            g_fail++;
        } else if (jepa_ac_context_n_frames(h) != n_seed + 1) {
            printf("  jepa_ac_context_update did not grow the handle\n");
            g_fail++;
        } else {
            std::vector<float> o1((size_t) K * 1 * HW * D), o2((size_t) K * 1 * HW * D);
            const int rc1 = jepa_ac_rollout_cached(ctx, h, acts.data(), nullptr, K, 1, o1.data());
            jepa_ac_context * h2 = jepa_ac_context_new(ctx, three.data(), n_seed + 1, a3.data(), s3.data());
            const int rc2 = h2 ? jepa_ac_rollout_cached(ctx, h2, acts.data(), nullptr, K, 1, o2.data()) : -1;
            if (rc1 != 0 || rc2 != 0) { printf("  update/rebuild rollout failed\n"); g_fail++; }
            else {
                double worst = 0;
                for (size_t i = 0; i < o1.size(); i++) worst = std::fmax(worst, std::fabs(o1[i] - o2[i]));
                const bool ok = worst == 0.0;
                if (!ok) g_fail++;
                printf("  %-44s max|d| = %.3e  %s\n", "context_update == rebuilt handle", worst,
                       ok ? "OK (bit-identical)" : "FAIL");
            }
            // trim() is a SLIDING WINDOW: it keeps the LAST n_keep frames. Trimming the 3-frame
            // handle to 2 therefore has to equal a handle built from frames [1, 2] — with their own
            // action between them and their own poses — not from [0, 1].
            if (jepa_ac_context_trim(h, n_seed) == 0 && jepa_ac_context_n_frames(h) == n_seed) {
                std::vector<float> last2((size_t) n_seed * HW * D), a2((size_t) (n_seed - 1) * A),
                                   s2((size_t) n_seed * S);
                memcpy(last2.data(), three.data() + (size_t) HW * D, last2.size() * sizeof(float));
                memcpy(a2.data(), a3.data() + (size_t) A, a2.size() * sizeof(float));
                memcpy(s2.data(), s3.data() + (size_t) S, s2.size() * sizeof(float));
                jepa_ac_context * h3 = jepa_ac_context_new(ctx, last2.data(), n_seed, a2.data(), s2.data());
                std::vector<float> o3((size_t) K * H * HW * D), o4((size_t) K * H * HW * D);
                const int r3 = jepa_ac_rollout_cached(ctx, h, acts.data(), nullptr, K, H, o3.data());
                const int r4 = h3 ? jepa_ac_rollout_cached(ctx, h3, acts.data(), nullptr, K, H, o4.data()) : -1;
                if (r3 != 0 || r4 != 0) { printf("  trim/rebuild rollout failed\n"); g_fail++; }
                else {
                    double worst = 0, moved = 0;
                    for (size_t i = 0; i < o3.size(); i++) {
                        worst = std::fmax(worst, std::fabs(o3[i] - o4[i]));
                        moved = std::fmax(moved, std::fabs(o3[i] - out[i]));
                    }
                    const bool ok = worst == 0.0;
                    if (!ok) g_fail++;
                    printf("  %-44s max|d| = %.3e  %s\n", "context_trim == handle of the last frames",
                           worst, ok ? "OK (bit-identical)" : "FAIL");
                    // and it really slid: the window [1,2] is not the window [0,1]
                    const bool slid = moved > 1e-2;
                    if (!slid) g_fail++;
                    printf("  %-44s max|d| vs the untrimmed prefix = %.3e  %s\n", "context_trim slid the window",
                           moved, slid ? "OK (> 1e-2)" : "FAIL (trim was a no-op)");
                }
                jepa_ac_context_free(h3);
            } else { printf("  jepa_ac_context_trim failed\n"); g_fail++; }
            jepa_ac_context_free(h2);
        }
    }
    jepa_ac_context_free(h);
    (void) gpu;
}

// The `cem` sample: Meta's own planner, run on the Franka demo data with every torch.randn draw
// recorded (scripts/dump_reference.py, "6."). torch's RNG cannot be replayed from C++, so the
// fixture stores the draws and jepa_ac_plan consumes them in the same order — which makes this a
// test of the ALGORITHM (sampling layout, clamps, elite selection, the unbiased std, the momentum
// update and the final rounding), the only part that can be wrong.
static void run_ac_cem(jepa_context * ctx, jepa_model * model, const std::string & ref,
                       const thresholds & thr) {
    const std::string cd = ref + "/cem";
    if (!exists(cd + ".cem_action.npy")) return;
    const int64_t D = jepa_model_embed_dim(model);
    const int64_t HW = jepa_ac_tokens_per_frame(model);
    const int A = jepa_ac_action_dim(model), S = jepa_ac_state_dim(model);
    int64_t r = 0, d = 0;
    std::vector<float> seed = load_f32(cd + ".context.npy", &r, &d);
    std::vector<float> goal = load_f32(cd + ".goal.npy", &r, &d);
    std::vector<float> st0  = load_f32(cd + ".state0.npy", &r, &d);
    npy::Array noise = npy::load(cd + ".cem_noise.npy");      // [steps, H, K, 4]
    std::vector<float> nz = noise.to_f32();
    npy::Array want = npy::load(cd + ".cem_action.npy");      // [H, 7]
    std::vector<float> wa = want.to_f32();
    if (noise.shape.size() != 4) { printf("  cem_noise has rank %zu\n", noise.shape.size()); g_fail++; return; }

    jepa_ac_cem_params q = jepa_ac_cem_default_params();
    q.cem_steps = (int) noise.shape[0];
    q.horizon   = (int) noise.shape[1];
    q.samples   = (int) noise.shape[2];
    q.topk      = 4;        // the fixture's AC_CEM
    q.momentum_mean = 0.15f;
    q.momentum_std  = 0.75f;
    q.momentum_mean_gripper = 0.15f;
    q.momentum_std_gripper  = 0.15f;

    jepa_ac_context * h = jepa_ac_context_new(ctx, seed.data(), 1, nullptr, st0.data());
    if (!h) { printf("  cem: jepa_ac_context_new failed\n"); g_fail++; return; }
    std::vector<float> got((size_t) q.horizon * A), best((size_t) q.cem_steps);
    const double t0 = jepa_context_last_compute_ms(ctx);
    (void) t0;
    if (jepa_ac_plan(ctx, h, goal.data(), &q, nz.data(), got.data(), best.data()) != 0) {
        printf("  cem: jepa_ac_plan failed\n");
        g_fail++;
        jepa_ac_context_free(h);
        return;
    }
    const double ms = jepa_context_last_compute_ms(ctx);
    double worst = 0, scale = 0;
    for (size_t i = 0; i < got.size(); i++) {
        worst = std::fmax(worst, std::fabs(got[i] - wa[i]));
        scale = std::fmax(scale, std::fabs(wa[i]));
    }
    // The plan is a handful of small numbers, so it is judged in absolute terms against the tier:
    // f32 on the CPU reproduces the reference planner's action to float32 round-off; a lossy file
    // moves the rollout, hence the energies, hence which candidates are elites.
    const double bar = thr.min_mean >= 0.9999 && thr.max_rel > 0 ? 1e-6 : 5e-3;
    const bool ok = worst <= bar;
    if (!ok) g_fail++;
    printf("  %-44s max|d| = %.3e over %d x %d (bar %.0e)  %8.2f ms  %s\n",
           "jepa_ac_plan vs Meta's cem()", worst, q.horizon, A, bar, ms, ok ? "OK" : "FAIL");
    printf("  %-44s ours [%.6f %.6f %.6f | %.6f]  reference [%.6f %.6f %.6f | %.6f]\n",
           "  plan, step 0 (dx dy dz | gripper)", got[0], got[1], got[2], got[6],
           wa[0], wa[1], wa[2], wa[6]);
    // the rotation dimensions must be exact zeros, as the reference's are
    bool zeros = true;
    for (int hh = 0; hh < q.horizon; hh++) {
        for (int j = 3; j < 6; j++) if (got[(size_t) hh * A + j] != 0.0f) zeros = false;
    }
    if (!zeros) g_fail++;
    printf("  %-44s %s\n", "  rotation dimensions are hard zeros", zeros ? "OK" : "FAIL");
    // the energy has to improve, or the loop is not optimising anything
    if (q.cem_steps > 1) {
        // Only the endpoints are compared: CEM is stochastic and a real run wanders (this fixture's
        // best energy rises again after iteration 3), so "non-increasing" would be a false claim.
        const bool better = best[(size_t) q.cem_steps - 1] <= best[0];
        if (!better) g_fail++;
        printf("  %-44s %.6f -> %.6f  %s\n", "  best energy, first vs last iteration", best[0],
               best[(size_t) q.cem_steps - 1], better ? "OK (final <= initial)" : "FAIL");
    }
    jepa_ac_context_free(h);
    (void) HW; (void) S; (void) D;
}

// The receding-horizon loop: one jepa_ac_context_update per observation, for as long as a planner
// would run. This exists because the handle used to allocate a fresh ggml_view_3d on every _update
// into a fixed-size ggml_context pool, so the third update aborted the process inside
// ggml_new_object() -- in Release, with no error path. The old parity test did exactly one _update
// and one _trim and sat one object under the limit, which is why it passed. Every step is checked
// against the explicit-context entry point over the same frames, so a handle that silently pointed
// at the wrong rows would fail here too.
static void run_ac_context_loop(jepa_context * ctx, jepa_model * model, const std::string & ref,
                                const thresholds & thr, bool gpu) {
    const std::string ro = ref + "/rollout";
    if (!exists(ro + ".context.npy")) return;
    (void) thr;
    const int64_t D = jepa_model_embed_dim(model);
    const int64_t HW = jepa_ac_tokens_per_frame(model);
    const int A = jepa_ac_action_dim(model), S = jepa_ac_state_dim(model);
    int64_t r = 0, d = 0;
    std::vector<float> seed = load_f32(ro + ".context.npy", &r, &d);
    std::vector<float> st0  = load_f32(ro + ".state0.npy", &r, &d);
    std::vector<float> acts = npy::load(ro + ".actions.npy").to_f32();     // [K, H, A]
    const int K = 2, H = 1, N_UPDATES = 6;
    const int64_t per_frame = HW * D;
    const int n_ref_h = (int) (acts.size() / (size_t) A) / 4;              // horizon of the fixture

    jepa_ac_context * h = jepa_ac_context_new(ctx, seed.data(), 1, nullptr, st0.data());
    if (!h) { printf("  context loop: jepa_ac_context_new failed\n"); g_fail++; return; }
    printf("  %-44s capacity %d frames, %d updates\n", "receding-horizon loop",
           jepa_ac_context_capacity(h), N_UPDATES);

    // host mirror of what the handle holds, for the explicit-context comparison
    std::vector<float> mirror(seed.begin(), seed.begin() + per_frame);
    std::vector<float> m_act, m_st(st0.begin(), st0.begin() + S);
    std::vector<float> cand((size_t) K * H * A);
    for (int c = 0; c < K; c++) {
        memcpy(cand.data() + (size_t) c * H * A, acts.data() + (size_t) c * n_ref_h * A,
               (size_t) A * sizeof(float));
    }

    bool ok_all = true;
    for (int step = 0; step < N_UPDATES && ok_all; step++) {
        std::vector<float> out_c((size_t) K * H * per_frame), out_e((size_t) K * H * per_frame);
        if (jepa_ac_rollout_cached(ctx, h, cand.data(), nullptr, K, H, out_c.data()) != 0) {
            printf("  context loop: rollout_cached failed at step %d\n", step);
            g_fail++;
            ok_all = false;
            break;
        }
        const int nf = jepa_ac_context_n_frames(h);
        if (jepa_ac_rollout_ex(ctx, mirror.data(), nf, nf > 1 ? m_act.data() : nullptr, m_st.data(),
                               cand.data(), nullptr, K, H, out_e.data()) != 0) {
            printf("  context loop: rollout_ex failed at step %d\n", step);
            g_fail++;
            ok_all = false;
            break;
        }
        double worst = 0;
        for (size_t i = 0; i < out_c.size(); i++) worst = std::fmax(worst, std::fabs(out_c[i] - out_e[i]));
        const bool ok = gpu ? worst <= 1e-2 : worst == 0.0;
        if (!ok) { g_fail++; ok_all = false; }
        char nm[96];
        snprintf(nm, sizeof(nm), "  update %d (%d frames): cached == explicit", step, nf);
        printf("  %-44s max|d| = %.3e  %s\n", nm, worst,
               ok ? (gpu ? "OK" : "OK (bit-identical)") : "FAIL");

        // append candidate 0's prediction as the next observed frame
        std::vector<float> next(out_c.begin(), out_c.begin() + per_frame);
        std::vector<float> nstate((size_t) S);
        jepa_ac_next_state(model, m_st.data() + (size_t) (nf - 1) * S, cand.data(), nstate.data());
        if (jepa_ac_context_update(h, next.data(), cand.data(), nstate.data()) != 0) {
            printf("  context loop: jepa_ac_context_update failed at step %d\n", step);
            g_fail++;
            ok_all = false;
            break;
        }
        mirror.insert(mirror.end(), next.begin(), next.end());
        m_act.insert(m_act.end(), cand.begin(), cand.begin() + A);
        m_st.insert(m_st.end(), nstate.begin(), nstate.end());
    }

    // a trim after the loop, then one more rollout, so the two paths interleave
    if (ok_all) {
        const int keep = 2;
        if (jepa_ac_context_trim(h, keep) != 0 || jepa_ac_context_n_frames(h) != keep) {
            printf("  context loop: trim failed\n");
            g_fail++;
        } else {
            const int64_t drop = (int64_t) (mirror.size() / per_frame) - keep;
            mirror.erase(mirror.begin(), mirror.begin() + drop * per_frame);
            m_act.erase(m_act.begin(), m_act.begin() + drop * A);
            m_st.erase(m_st.begin(), m_st.begin() + drop * S);
            std::vector<float> out_c((size_t) K * H * per_frame), out_e((size_t) K * H * per_frame);
            const int r1 = jepa_ac_rollout_cached(ctx, h, cand.data(), nullptr, K, H, out_c.data());
            const int r2 = jepa_ac_rollout_ex(ctx, mirror.data(), keep, m_act.data(), m_st.data(),
                                              cand.data(), nullptr, K, H, out_e.data());
            if (r1 != 0 || r2 != 0) { printf("  context loop: post-trim rollout failed\n"); g_fail++; }
            else {
                double worst = 0;
                for (size_t i = 0; i < out_c.size(); i++) worst = std::fmax(worst, std::fabs(out_c[i] - out_e[i]));
                const bool ok = gpu ? worst <= 1e-2 : worst == 0.0;
                if (!ok) g_fail++;
                printf("  %-44s max|d| = %.3e  %s\n", "  trim to 2, then cached == explicit", worst,
                       ok ? (gpu ? "OK" : "OK (bit-identical)") : "FAIL");
            }
        }
    }
    jepa_ac_context_free(h);
}

int main(int argc, char ** argv) {
    std::string lewm_path, vjepa2_path, ac_path, ref, case_dir, samples_arg = "archery_f16", modality_arg = "video";
    jepa_context_params cp = jepa_context_default_params();
    jepa_model_params   mp = jepa_model_default_params();
    double min_cos = -1, max_rel = -1;
    for (int i = 1; i < argc; i++) {
        std::string a = argv[i];
        auto next = [&]() -> const char * { if (i + 1 >= argc) { fprintf(stderr, "%s needs a value\n", a.c_str()); exit(2); } return argv[++i]; };
        if (a == "--lewm") lewm_path = next();
        else if (a == "--vjepa2") vjepa2_path = next();
        else if (a == "--ac") ac_path = next();
        else if (a == "--ref") ref = next();
        else if (a == "--case") case_dir = next();
        else if (a == "--samples") samples_arg = next();
        else if (a == "--threads" || a == "-t") cp.n_threads = atoi(next());
        else if (a == "--gpu") {
            mp.device = 0;
            if (i + 1 < argc && argv[i + 1][0] >= '0' && argv[i + 1][0] <= '9') mp.device = atoi(argv[++i]);
        }
        else if (a == "--no-flash") cp.use_flash_attn = false;
        else if (a == "--kv-f32") cp.flash_kv = JEPA_KV_F32;
        else if (a == "--kv-f16") cp.flash_kv = JEPA_KV_F16;
        else if (a == "--min-cos") min_cos = atof(next());
        else if (a == "--modality") modality_arg = next();
        else if (a == "--quiet") g_quiet = true;
        else if (a == "-h" || a == "--help") {
            printf("usage: %s --lewm MODEL.gguf --ref REFDIR | --vjepa2 MODEL.gguf {--ref REFDIR [--samples a,b] | --case DIR}\n"
                   "       | --ac MODEL.gguf --ref REFDIR   (V-JEPA 2-AC world model)\n"
                   "       [--threads N] [--gpu [N]] [--no-flash] [--kv-f32|--kv-f16] [--min-cos X]\n"
                   "       [--modality auto|video|image]   (V-JEPA 2.1 pred.mod_embed_*, default video)\n"
                   "       [--quiet]\n", argv[0]);
            return 0;
        } else { fprintf(stderr, "unknown argument %s\n", argv[i]); return 2; }
    }
    const int n_modes = (int) !lewm_path.empty() + (int) !vjepa2_path.empty() + (int) !ac_path.empty();
    if (n_modes != 1) { fprintf(stderr, "need exactly one of --lewm / --vjepa2 / --ac\n"); return 2; }
    const int modality = modality_arg == "auto" ? JEPA_MODALITY_AUTO : modality_arg == "image" ? JEPA_MODALITY_IMAGE
                       : modality_arg == "video" ? JEPA_MODALITY_VIDEO : -1;
    if (modality < 0) { fprintf(stderr, "--modality must be auto, video or image (got '%s')\n", modality_arg.c_str()); return 2; }

    const std::string model_path = !lewm_path.empty() ? lewm_path : !vjepa2_path.empty() ? vjepa2_path : ac_path;
    jepa_model * model = jepa_model_load_ex(model_path.c_str(), &mp);
    if (!model) return 2;
    jepa_context * c = jepa_context_new(model, cp);
    if (!c) return 2;
    const int ftype = jepa_model_file_type(model);
    thresholds thr = thresholds_for(ftype, jepa_model_is_gpu(model));
    if (min_cos > 0) { thr.min_mean = thr.min_min = min_cos; thr.max_rel = -1; }
    printf("model: %s (%s, %s) | device %s | threads %d | flash %s | modality %s | thresholds cos_mean >= %g, cos_min >= %g%s\n",
           jepa_model_name(model), jepa_model_family(model), jepa_model_file_type_name(model),
           jepa_model_device_name(model),
           jepa_context_n_threads(c), cp.use_flash_attn ? "yes" : "no", modality_arg.c_str(), thr.min_mean, thr.min_min,
           thr.max_rel > 0 ? ", rel <= bound*max(1,sqrt(rows/2048))" : "");

    if (!lewm_path.empty()) run_lewm(c, model, ref, thr, ftype != 0);
    if (!ac_path.empty()) {
        run_ac(c, model, ref, thr, jepa_model_is_gpu(model));
        run_ac_seed2(c, model, ref, thr, jepa_model_is_gpu(model));
        run_ac_cem(c, model, ref, thr);
        run_ac_context_loop(c, model, ref, thr, jepa_model_is_gpu(model));
    }
    if (!vjepa2_path.empty()) {
        if (!case_dir.empty()) run_case(c, case_dir, thr, modality);
        if (!ref.empty()) {
            std::vector<std::string> samples;
            size_t p = 0;
            while (p <= samples_arg.size() && !samples_arg.empty()) {
                size_t q = samples_arg.find(',', p);
                if (q == std::string::npos) { samples.push_back(samples_arg.substr(p)); break; }
                samples.push_back(samples_arg.substr(p, q - p));
                p = q + 1;
            }
            run_vjepa2(c, model, ref, samples, thr, modality);
        }
    }
    jepa_context_free(c);
    jepa_model_free(model);
    printf("%s\n", g_fail == 0 ? "PASS" : "FAIL");
    return g_fail == 0 ? 0 : 1;
}
