#!/usr/bin/env python3
"""Render the generated tables of docs/serving.md from tests/results/server-bench.json.

    scripts/render_serving_md.py                        # print the block to stdout
    scripts/render_serving_md.py --write docs/serving.md    # splice it into the doc
    scripts/render_serving_md.py --check                 # exit 1 if the doc is stale (CI)

One throughput/latency table per backend (rows: --max-batch x concurrency), the planner memory
table, and the environment line, so no number on that page is ever retyped by hand. `--write`
replaces the region between the BEGIN/END markers and leaves the prose alone; the prose *around* the
markers still has to be edited by a human when the numbers move enough to change what they say.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BEGIN = "<!-- BEGIN generated by scripts/render_serving_md.py from tests/results/server-bench.json -->"
END = "<!-- END generated -->"

BACKENDS = [
    ("cpu", "CPU — LeJEPA ViT-S/16 f16, 32 threads, 1 worker"),
    ("gpu", "GPU — I-JEPA ViT-H/14 f16, device 1, 1 worker"),
]


def num(x, fmt="{:.1f}"):
    return "–" if x is None else fmt.format(x)


def cell_table(rows: list) -> str:
    """One row per measured cell — `--max-batch` x concurrency — and the metrics across."""
    ordered = sorted(rows, key=lambda r: (r["max_batch"], r["concurrency"]))
    best = max(r["req_per_s"] for r in ordered)
    out = [
        "| `--max-batch` | clients | req/s | p50 ms | p95 ms | p99 ms | mean batch | graphs |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in ordered:
        rps = num(r["req_per_s"], "{:.1f}")
        if r["req_per_s"] == best:
            rps = f"**{rps}**"
        out.append(
            f"| {r['max_batch']} | {r['concurrency']} | {rps} | {num(r['p50_ms'], '{:.0f}')} | "
            f"{num(r['p95_ms'], '{:.0f}')} | {num(r['p99_ms'], '{:.0f}')} | "
            f"{num(r['mean_batch'], '{:.1f}')} | {r['graphs']} |"
        )
    return "\n".join(out)


def control_line(rows: list) -> str:
    """What the harness itself could drive, which is the ceiling every cell sits under."""
    if not rows:
        return ""
    lo = min(r["health_req_per_s"] for r in rows)
    hi = max(r["health_req_per_s"] for r in rows)
    peak = max(r["req_per_s"] for r in rows)
    return (f"The `GET /health` control ran at {lo:.0f}–{hi:.0f} req/s over the same cells, against a "
            f"best measured {peak:.1f} req/s of real work — a factor of {lo / peak:.0f} of headroom, "
            f"so these cells are measuring the server.")


def planner_table(rows: list) -> str:
    if not rows:
        return "_No planner measurement in this artifact._"
    out = [
        "| concurrent planners | peak device MiB | added per planner | rollout/s | p50 ms | p99 ms |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    prev = None
    for r in rows:
        added = "–" if prev is None else f"{(r['peak_mib'] - prev['peak_mib']) / (r['workers'] - prev['workers']):.0f}"
        out.append(
            f"| {r['workers']} | {r['peak_mib']} | {added} | {r['req_per_s']:.2f} | "
            f"{r['p50_ms']:.0f} | {r['p99_ms']:.0f} |"
        )
        prev = r
    return "\n".join(out)


def env_table(d: dict) -> str:
    b = d["box"]
    return "\n".join([
        "| | |",
        "|---|---|",
        f"| CPU | {b['cpu']}, {b['cores']} threads |",
        f"| Build | {b['compiler']}, ggml `{b['ggml_commit']}`, `GGML_LLAMAFILE={b['ggml_llamafile']}`, "
        f"kernel {b['kernel']} |",
        f"| GPU | {b.get('device', '–')}, {b.get('device_memory', '–')}, compute {b.get('compute_cap', '–')}, "
        f"{b.get('power_limit', '–')} board limit, driver {b.get('driver', '–')} |",
        f"| Client | Python {b['python']}, `jepa_cpp.client` over `urllib` |",
        f"| Commit | `{b['git_commit']}`, jepa.cpp {d['jepa_version']} |",
        f"| Date | {d['session']['start_utc']}, {d['session']['note']} |",
    ])


def render(d: dict) -> str:
    parts = ["### Environment", "", env_table(d), ""]
    for key, title in BACKENDS:
        rows = d.get(key) or []
        parts += [f"### {title}", ""]
        if not rows:
            parts += ["_Not measured in this artifact._", ""]
            continue
        n = rows[0]["requests"]
        parts += [
            cell_table(rows),
            "",
            f"{n} requests per cell, {d['session']['warmup']} warmup, one 640×480 COCO JPEG each. "
            + control_line(rows),
            "",
        ]
    plan = d.get("planner") or []
    parts += ["### Device memory per concurrent planner", ""]
    if plan:
        r = plan[0]
        parts += [
            planner_table(plan),
            "",
            f"V-JEPA 2-AC ViT-g f16 on device {r['device']}, {r['candidates']} candidates × "
            f"{r['horizon']} steps per request, {r['weights_mib']:.0f} MiB of weights. The card holds "
            f"{r['idle_mib']} MiB idle, {r['loaded_mib']} MiB with the model resident and nothing "
            f"running, and {r['warm_one_planner_mib']} MiB once one planner has built its graphs.",
            "",
        ]
    else:
        parts += ["_Not measured in this artifact._", ""]
    return "\n".join(parts)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", type=Path, default=ROOT / "tests/results/server-bench.json")
    ap.add_argument("--write", type=Path, help="splice the block into this file")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the block in --write (default docs/serving.md) is stale, "
                         "instead of rewriting it")
    a = ap.parse_args()
    block = render(json.loads(a.json.read_text()))
    target = a.write or (ROOT / "docs" / "serving.md" if a.check else None)
    if target is None:
        print(block, end="")
        return
    md = target.read_text()
    i, j = md.find(BEGIN), md.find(END)
    if i < 0 or j < 0:
        raise SystemExit(f"{target}: missing the {BEGIN!r} / {END!r} markers")
    spliced = md[:i] + BEGIN + "\n\n" + block + "\n" + md[j:]
    if a.check:
        if spliced != md:
            print(f"{target} is stale — run scripts/render_serving_md.py --write {target}",
                  file=sys.stderr)
            raise SystemExit(1)
        print(f"{target} is up to date")
        return
    target.write_text(spliced)
    print(f"wrote the generated block into {target}")


if __name__ == "__main__":
    main()
