#!/usr/bin/env python3
"""Render the generated tables of docs/accuracy-image.md from tests/results/accuracy-image.json.

    scripts/render_accuracy_md.py                              # print the block to stdout
    scripts/render_accuracy_md.py --write docs/accuracy-image.md   # splice it into the doc

One accuracy table per model (rows: backend/dtype x feature x gallery), the flip table, and the
throughput table, so no number in the doc is ever retyped by hand.  `--write` replaces the region
between the BEGIN/END markers in the target file and leaves the prose alone; the prose *around* the
markers still has to be edited by a human when the numbers move enough to change what they say.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BEGIN = "<!-- BEGIN generated by scripts/render_accuracy_md.py from tests/results/accuracy-image.json -->"
END = "<!-- END generated -->"

TITLE = {
    "ijepa-vith14-1k": "I-JEPA ViT-H/14 (`ijepa_vith14_1k`) — feature = mean of the 256 patch tokens",
    "lejepa-vits16": "LeJEPA ViT-S/16 (`lejepa-vits16-pretrain-in1k`)",
    "lewm-pusht": "LeWorldModel encoder (`lewm-pusht`) — feature = `emb` = enc.proj(CLS), sanity row",
}
GAL = {"train2000": "2 000 (200/class)", "train_full": "9 469 (full train)"}


def pct(x):
    return "—" if x is None else f"{100 * x:.2f}"


def occupancy_line(timing: dict) -> str:
    """One sentence on how idle the box was while the throughput table was measured.

    `uptime`'s load average cannot say that on its own — a back-to-back sweep of 32-thread passes
    holds it near 32 however idle the machine is — so every pass also brackets itself with
    /proc/stat (CPU-seconds the whole box spent out of idle) and os.times() (CPU-seconds this
    process tree spent).  What is left over is somebody else's work.
    """
    occ = [v["occupancy"] for v in timing.values() if v.get("occupancy")]
    if not occ:
        return ""
    mach = sum(o["machine_cpu_s"] for o in occ)
    own = sum(o["own_cpu_s"] for o in occ)
    foreign = sum(o["foreign_cpu_s"] for o in occ)
    wall = sum(o["wall_s"] for o in occ)
    return (f"Measured back-to-back in one sweep on an otherwise idle box: over the {len(occ)} timed "
            f"passes above the machine spent {mach / 60:.0f} CPU-minutes out of idle, "
            f"{own / 60:.0f} of them this benchmark's own process trees, leaving "
            f"{foreign / 60:.1f} CPU-minutes — an average of {foreign / max(wall, 1e-9):.2f} of one "
            f"core out of 96 — for everything else on the machine (`occupancy` per row in the JSON: "
            f"/proc/stat non-idle minus os.times() self+children).")


def render(d: dict) -> str:
    L = []
    A = L.append
    rows = d["rows"]
    for m in dict.fromkeys(r["model"] for r in rows):
        A(f"### {TITLE.get(m, m)}\n")
        A("| backend | dtype | feature | gallery | kNN top-1 % | centroid top-1 % | "
          "agreement % | mean feat cos | worst feat cos | img/s |")
        A("|---|---|---|---|---|---|---|---|---|---|")
        rs = [r for r in rows if r["model"] == m]
        rs.sort(key=lambda r: (r["feature"], r["gallery"], r["backend"] != "pytorch"))
        for r in rs:
            torchrow = r["backend"] == "pytorch"
            cos = "1" if torchrow else f"{r['feat_cos_mean']:.6f}"
            wcos = "1" if torchrow else f"{r['feat_cos_min']:.6f}"
            agr = "—" if torchrow else pct(r["agreement"])
            ips = "—" if r.get("img_per_s") is None else f"{r['img_per_s']:.1f}"
            A(f"| {r['backend']} | {r['dtype']} | {r['feature']} | {GAL.get(r['gallery'], r['gallery'])} | "
              f"{pct(r['knn_top1'])} | {pct(r['centroid_top1'])} | {agr} | {cos} | {wcos} | {ips} |")
        A("")

    A("### Where the predictions differ (largest gallery of each model)\n")
    A("| model | feature | dtype | items flipped vs PyTorch | PyTorch right | jepa.cpp right | "
      "both wrong | median NN margin of the flipped items | median NN margin, all items |")
    A("|---|---|---|---|---|---|---|---|---|")
    for m in dict.fromkeys(r["model"] for r in rows):
        big = max(r["n_gallery"] for r in rows if r["model"] == m)
        for r in rows:
            if r["model"] != m or r["backend"] == "pytorch" or r["n_gallery"] != big:
                continue
            mf = r.get("margin_flipped_median")
            A(f"| {m} | {r['feature']} | {r['dtype']} | {r['n_flipped']} / {r['n_query']} | "
              f"{r['flip_pytorch_right']} | {r['flip_jepacpp_right']} | {r['flip_both_wrong']} | "
              f"{'—' if mf is None else f'{mf:+.4f}'} | {r['margin_all_median']:+.4f} |")
    A("")

    A("### Throughput (32 threads, end-to-end: JPEG decode + preprocess + encode)\n")
    A("| backend | model | dtype | split | images | wall s | img/s |")
    A("|---|---|---|---|---|---|---|")
    # a sweep may run its passes in any order (they are deliberately interleaved between backends);
    # the table is always printed model-major, PyTorch first, then dtype and split
    morder = list(dict.fromkeys(r["model"] for r in rows))
    dorder = ["f32", "f16", "q8_0", "q4_k"]
    sorder = ["train2000", "train_full", "val", "val1000"]

    def tkey(k):
        be, m, dt, sp = k.split("|")
        idx = lambda seq, v: seq.index(v) if v in seq else len(seq)     # noqa: E731
        return (idx(morder, m), be != "torch", idx(dorder, dt), idx(sorder, sp))

    for k in sorted(d["timing"], key=tkey):
        v = d["timing"][k]
        be, m, dt, sp = k.split("|")
        # rows recorded before jepa-embed grew --batch carry no "batch" key: those were 1 img/call
        be = "PyTorch, batch 32" if be == "torch" else f"jepa-embed, batch {v.get('batch', 1)}"
        A(f"| {be} | {m} | {dt} | {sp} | {v['n']} | {v['wall_s']:.1f} | {v['img_per_s']:.2f} |")
    line = occupancy_line(d["timing"])
    if line:
        A("")
        A(line)
    A("")

    g = d.get("graph_time") or {}
    if g:
        one = next(iter(g.values()))
        A(f"### Graph compute alone (`jepa-embed --time --repeat {one['repeat']}`, "
          f"{one['n_images']} query images, {one['threads']} threads)\n")
        A("| model | dtype | GGUF | ms / image (min–max) | median |")
        A("|---|---|---|---|---|")
        for k in sorted(g, key=lambda k: (morder.index(k.split("|")[0])
                                          if k.split("|")[0] in morder else 99,
                                          dorder.index(k.split("|")[1])
                                          if k.split("|")[1] in dorder else 99)):
            v = g[k]
            m, dt = k.split("|")
            A(f"| {m} | {dt} | `{v['gguf']}` | {v['ms_min']}–{v['ms_max']} | {v['ms_median']} |")
        A("")
        A("The same already-preprocessed image encoded twice per row, with the JPEG decode, the "
          "preprocessing and the model load all outside the number — the throughput table above "
          "contains all three, this table contains none of them.")
        A("")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("json", nargs="?", type=Path, default=ROOT / "tests/results/accuracy-image.json")
    ap.add_argument("--write", type=Path, help="splice the block into this markdown file, between "
                                               "the BEGIN/END markers")
    a = ap.parse_args()
    block = render(json.loads(a.json.read_text()))
    if not a.write:
        print(block, end="")
        return
    md = a.write.read_text()
    i, j = md.find(BEGIN), md.find(END)
    if i < 0 or j < 0:
        raise SystemExit(f"{a.write}: missing the {BEGIN!r} / {END!r} markers")
    a.write.write_text(md[:i] + BEGIN + "\n\n" + block + "\n" + md[j:])
    print(f"wrote the generated block into {a.write}")


if __name__ == "__main__":
    main()
